deployment:
  svc: true
  bff: true
  ui: true

product:
  info:
    data:
      description: "OneCX Announcement"
      imageUrl: ""
      iconName: "bullhorn"
      displayName: "OneCX Announcement"
      basePath: "/announcement"
